// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARFs0HEteA0PbATO8CIe8q_8VDZYz3e5Y',
    appId: '1:924224930201:web:86439cdc4473cac2141308',
    messagingSenderId: '924224930201',
    projectId: 'redox-backend',
    authDomain: 'redox-backend.firebaseapp.com',
    storageBucket: 'redox-backend.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEYSjIuyO9jFtCkgrTt1f-Z-suzDFYfUU',
    appId: '1:924224930201:android:b9f85cf8f5e974a3141308',
    messagingSenderId: '924224930201',
    projectId: 'redox-backend',
    storageBucket: 'redox-backend.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1dFPWAliv5KUluvC8YzUJC0apCTmQ0sM',
    appId: '1:924224930201:ios:5268fdf2dc9a644d141308',
    messagingSenderId: '924224930201',
    projectId: 'redox-backend',
    storageBucket: 'redox-backend.appspot.com',
    iosBundleId: 'com.example.redoxUi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1dFPWAliv5KUluvC8YzUJC0apCTmQ0sM',
    appId: '1:924224930201:ios:f20693bbd048b1ec141308',
    messagingSenderId: '924224930201',
    projectId: 'redox-backend',
    storageBucket: 'redox-backend.appspot.com',
    iosBundleId: 'com.example.redoxUi.RunnerTests',
  );
}
